import { MigrationInterface, QueryRunner } from "typeorm";

export class profile1668011282577 implements MigrationInterface {
    name = 'profile1668011282577'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_765e6e96f746be07e7de6274685\``);
        await queryRunner.query(`DROP INDEX \`REL_765e6e96f746be07e7de627468\` ON \`users\``);
        await queryRunner.query(`ALTER TABLE \`ticket_statuses\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`ticket_statuses\` DROP COLUMN \`code\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`password\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`phone_number\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`account_status\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`paid_amount\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`first_name\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`last_name\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`birthday\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`identification_id_obj\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`passport_obj\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`gender\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`national_id\``);
        await queryRunner.query(`ALTER TABLE \`ticket_statuses\` DROP COLUMN \`status_name\``);
        await queryRunner.query(`ALTER TABLE \`ticket_statuses\` ADD \`status_name\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`first_name\` varchar(50) CHARACTER SET "utf8" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`last_name\` varchar(50) CHARACTER SET "utf8" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`birthday\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`identification_id_obj\` varchar(20) CHARACTER SET "utf8" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`passport_obj\` varchar(20) CHARACTER SET "utf8" NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`gender\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`national_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`religion_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`ethnicity_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`marital_status_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`workEmail\` varchar(255) CHARACTER SET "utf8" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`tax_number\` varchar(255) CHARACTER SET "utf8" NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`health_insurance_number\` varchar(255) CHARACTER SET "utf8" NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`health_insurance_place\` varchar(255) CHARACTER SET "utf8" NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`join_date\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`end_date\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`bhxh_date\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`bhyt_date\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`phone_number\` varchar(20) CHARACTER SET "utf8" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`company_name\` varchar(20) CHARACTER SET "utf8" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`account_status\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`password\` varchar(255) CHARACTER SET "utf8" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`paid_amount\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_765e6e96f746be07e7de627468\` (\`paid_amount\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`user_personal\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_e73079c75eff0289cd2478b68f\` (\`user_personal\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`user_work\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_0c43b28075895eb7c448e15214\` (\`user_work\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`email\` varchar(255) CHARACTER SET "utf8" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`city\` varchar(20) CHARACTER SET "utf8" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`state\` varchar(20) CHARACTER SET "utf8" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`address_1\` varchar(20) CHARACTER SET "utf8" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`address_2\` varchar(20) CHARACTER SET "utf8" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`country_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`ticket_statuses\` ADD \`name\` varchar(255) CHARACTER SET "utf8" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`ticket_statuses\` ADD \`code\` int NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_765e6e96f746be07e7de627468\` ON \`users\` (\`paid_amount\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_e73079c75eff0289cd2478b68f\` ON \`users\` (\`user_personal\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_0c43b28075895eb7c448e15214\` ON \`users\` (\`user_work\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_765e6e96f746be07e7de6274685\` FOREIGN KEY (\`paid_amount\`) REFERENCES \`paid_amounts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_e73079c75eff0289cd2478b68ff\` FOREIGN KEY (\`user_personal\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_0c43b28075895eb7c448e15214c\` FOREIGN KEY (\`user_work\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_0c43b28075895eb7c448e15214c\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_e73079c75eff0289cd2478b68ff\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_765e6e96f746be07e7de6274685\``);
        await queryRunner.query(`DROP INDEX \`REL_0c43b28075895eb7c448e15214\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`REL_e73079c75eff0289cd2478b68f\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`REL_765e6e96f746be07e7de627468\` ON \`users\``);
        await queryRunner.query(`ALTER TABLE \`ticket_statuses\` DROP COLUMN \`code\``);
        await queryRunner.query(`ALTER TABLE \`ticket_statuses\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`country_id\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`address_2\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`address_1\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`state\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`city\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_0c43b28075895eb7c448e15214\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`user_work\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_e73079c75eff0289cd2478b68f\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`user_personal\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_765e6e96f746be07e7de627468\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`paid_amount\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`password\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`account_status\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`company_name\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`phone_number\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`bhyt_date\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`bhxh_date\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`end_date\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`join_date\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`health_insurance_place\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`health_insurance_number\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`tax_number\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`workEmail\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`marital_status_id\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`ethnicity_id\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`religion_id\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`national_id\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`gender\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`passport_obj\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`identification_id_obj\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`birthday\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`last_name\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`first_name\``);
        await queryRunner.query(`ALTER TABLE \`ticket_statuses\` DROP COLUMN \`status_name\``);
        await queryRunner.query(`ALTER TABLE \`ticket_statuses\` ADD \`status_name\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`national_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`gender\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`passport_obj\` varchar(20) CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`identification_id_obj\` varchar(20) CHARACTER SET "utf8" COLLATE "utf8_general_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`birthday\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`last_name\` varchar(50) CHARACTER SET "utf8" COLLATE "utf8_general_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`first_name\` varchar(50) CHARACTER SET "utf8" COLLATE "utf8_general_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`paid_amount\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`account_status\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`phone_number\` varchar(20) CHARACTER SET "utf8" COLLATE "utf8_general_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`email\` varchar(255) CHARACTER SET "utf8" COLLATE "utf8_general_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`password\` varchar(255) CHARACTER SET "utf8" COLLATE "utf8_general_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`name\` varchar(255) CHARACTER SET "utf8" COLLATE "utf8_general_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`ticket_statuses\` ADD \`code\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`ticket_statuses\` ADD \`name\` varchar(255) CHARACTER SET "utf8" COLLATE "utf8_general_ci" NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_765e6e96f746be07e7de627468\` ON \`users\` (\`paid_amount\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_765e6e96f746be07e7de6274685\` FOREIGN KEY (\`paid_amount\`) REFERENCES \`paid_amounts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
